version: '3.8'  # Đảm bảo đúng phiên bản

services:
  website:
    build: ./website
    container_name: website
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/chatapp"
    networks:
      - chat-net

  chat:
    build: ./chat
    container_name: chat
    ports:
      - "8001:8001"
    depends_on:
      - db
    networks:
      - chat-net

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatapp
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  # Khởi tạo bảng mới từ file init.sql
    networks:
      - chat-net


  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80"  # Thay đổi cổng bên ngoài thành 8080 nếu cần
    depends_on:
      - website
      - chat
    networks:
      - chat-net

networks:
  chat-net:
    driver: bridge
